### ISSUE TITLE
[Issue] Repairing constructors while they're building

### ISSUE THREAD

**Issue by rogual** [KatekovAnton/MACS-docs#64] opened 2021-01-04 00:25 UTC
A repair unit can repair a constructor while it's building something, but only if you click on the square the constructor was in just before it started building.

I would expect to be able to repair the constructor by clicking any of the 4 squares of the construction site.

**Comment by Hruks** [comment] 2021-01-12 09:12
Looks like expected behavior should be: repair unit can not interact with busy constructor.

**Comment by Hruks** [comment] 2024-04-03 13:20
Final solution: Repair, Steal and Disable actions works on any cells of construction site
MR submitted: https://gitlab.com/void0main/maxtouch-external/-/merge_requests/134

**Comment by KatekovAnton** [comment] 2024-04-11 16:54
Reviewing it

**Comment by KatekovAnton** [comment] 2024-04-26 14:39
Will be released in v19.1.0

**Closed by KatekovAnton** 2024-04-26 14:39 UTC
